---
:mailboxes:
  -
    :email: "tryittiny@gmail.com"
    :password: "testpassword1234"
    :name: "inbox"
    :delivery_method: postback
    :delivery_options:
      :delivery_url: "http://localhost:3000/inbox"
      :delivery_token: "abcdefg"